import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Rocket Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="sm:scroll-smooth">
      <body className="min-h-screen bg-slate-50 dark:bg-slate-950 dark :text-white">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
